deployment:
  tasks:
    - export DEPLOYPATH="/home/boxindus/public_html"
    - /usr/bin/rsync -a --delete --exclude='.git' --exclude='.cpanel.yml' ./ "$DEPLOYPATH"
    - date > "$DEPLOYPATH/deploy.ok"